version: '3.8'

services:
  create-dessert-service:
    build: ./dessert/create-dessert-service  # Ruta al Dockerfile del servicio de creación
    ports:
      - "4014:4014"  # Mapea el puerto del contenedor al puerto del host
    networks:
      - dessert-network

  delete-dessert-service:
    build: ./dessert/delete-dessert-service  # Ruta al Dockerfile del servicio de eliminación
    ports:
      - "4016:4016"
    networks:
      - dessert-network

  read-dessert-service:
    build: ./dessert/read-dessert-service  # Ruta al Dockerfile del servicio de lectura
    ports:
      - "4019:4019"
    networks:
      - dessert-network

  update-dessert-service:
    build: ./dessert/update-dessert-service  # Ruta al Dockerfile del servicio de actualización
    ports:
      - "4011:4011"
    networks:
      - dessert-network

networks:
  dessert-network:
    driver: bridge
