name: Deploy Microservices to EC2Dessert

on:
  push:
    paths:
      - "dessert/**"
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build and Deploy Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y subir las imágenes de Docker
      - name: Build and Push Docker image for create-dessert-service
        uses: docker/build-push-action@v2
        with:
          context: ./dessert/create-dessert-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/create-dessert-service:latest

      - name: Build and Push Docker image for delete-dessert-service
        uses: docker/build-push-action@v2
        with:
          context: ./dessert/delete-dessert-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/delete-dessert-service:latest

      - name: Build and Push Docker image for read-dessert-service
        uses: docker/build-push-action@v2
        with:
          context: ./dessert/read-dessert-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/read-dessert-service:latest

      - name: Build and Push Docker image for update-dessert-service
        uses: docker/build-push-action@v2
        with:
          context: ./dessert/update-dessert-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/update-dessert-service:latest

      # Desplegar los microservicios en EC2 usando SSH y Docker Compose
      - name: Deploy services to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTDESSERT }} # Dirección IP de tu EC2
          username: ${{ secrets.USERNAME }} # Tu usuario de EC2
          key: ${{ secrets.EC2_SSH_KEY }} # Clave SSH para la autenticación
          script: |
            # Actualiza el sistema y Docker
            sudo apt-get -y update
            sudo apt-get install -y docker.io docker-compose

            # Detener y eliminar contenedores existentes si es necesario
            sudo docker-compose -f /path/to/your/docker-compose.yml down

            # Obtener las últimas imágenes de Docker desde Docker Hub
            sudo docker-compose -f /path/to/your/docker-compose.yml pull

            # Ejecutar los contenedores de los servicios
            sudo docker-compose -f /path/to/your/docker-compose.yml up -d
